### ISSUE TITLE
FormsySelect onChange getting bypassed

### ISSUE THREAD

**Issue by scrambled2k3** [rojobuffalo/formsy-material-ui#225]
I just updated to version 0.6.1 it noticed the behavior of the FormsySelect onChange function has changed.  It appears that the callback parameters are now returning as (event, index, value) instead of (event, value, index) as they have been.

Diving in a little more, it looks like onChange is being past down to the SelectField component via the ...rest spread object so it is being called there (which is returning back event, index, value).

**Comment by rojobuffalo** [comment]
Ok, thanks for raising the issue. Sounds like maybe an unintended side-effect of some changes made to upgrade the eslint configuration.

**Comment by rojobuffalo** [comment]
I just pushed a patch to master. I wish I had time to write a proper test, but do you want to check to see if that patch works? I'll publish `v0.6.2` if you confirm that it's fixed.

**Comment by scrambled2k3** [comment]
Thanks @rojobuffalo, that does seem to fix it!
