### ISSUE TITLE
FormsyText with type="number" bad behavior

### ISSUE THREAD

**Issue by cristianocca** [rojobuffalo/formsy-material-ui#228]
Using material-ui TextField with type="number" correctly prevents the input from loading non numeric values, just like native inputs that supports it (firefox, chrome).

However, when using it with formsy-material-ui, the input still allows non numeric values to be typed, and they are displayed on the input, although it looks like the value never gets validated and always end up as an empty value, but looks bad. This happens on firefox or IE/Edge, chrome doesn't seem to have this issue.

Version 0.6.0

**Comment by rojobuffalo** [comment]
I just tested plain Material UI in Firefox with `type="number"` and it was letting alphabetic characters through. How did you test it?

**Comment by cristianocca** [comment]
Hmm, that's odd, I'm sure I tested it on firefox and edge and it worked, but I can't reproduce it anymore, it always lets non numeric values to be entered, it doesn't matter if I use TextField or even plain input components. Sorry for the false report.

**Comment by rojobuffalo** [comment]
No worries. I like the Chrome behavior of only allowing numeric characters, but I guess it isn't standard across browsers. If you want to enforce something like that, you could probably get there with [`convertValue`][1].

[1]: https://github.com/rojobuffalo/formsy-material-ui/blob/master/src/FormsyText.jsx#L12
